- name: create/update lifecycle environments
  redhat.satellite.lifecycle_environment:
    username: "{{ item.0.admin_username }}"
    password: "{{ item.0.admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    label: "{{ item.1.label | default(omit) }}"
    organization: "{{ item.0.name }}"
    prior: "{{ item.1.prior }}"
    description: "{{ item.1.desc | default(omit) }}"
    state: "{{ item.1.state }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - lifecycle_environments
  loop_control:
    label: "{{ item.1.name }}"
  tags: [katello,lcenv]

