---
- name: taxonomies | create Organizations
  redhat.satellite.organization:
    username: "{{ item.admin_username }}"
    password: "{{ item.admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ satellite_orgs }}"
  loop_control:
    label: "{{ item.name }}"
  tags: [katello,taxonomies,org]

- name: taxonomies | create locations
  redhat.satellite.location:
    username: "{{ item.0.admin_username }}"
    password: "{{ item.0.admin_password }}"
    server_url: "{{ satellite_url }}"
    validate_certs: "{{ satellite_verify_ssl }}"
    name: "{{ item.1.name }}"
    state: "{{ item.1.state }}"
    organizations:
      - "{{ item.0.name }}"
  with_subelements:
    - "{{ satellite_orgs }}"
    - locations
  loop_control:
    label: "{{ item.1.name }}"
  tags: [katello,taxonomies,location]
